// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gts_gui_ja_h
#define gts_gui_ja_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "fl_gl_image_view.h"
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include "cb_area_and_rot90.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Value_Output.H>
#include "cb_pixel_type_and_bright.h"
#include <FL/Fl_Box.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>
#include "cb_trace_params.h"
#include "fl_gl_hsv_view.h"
#include <FL/Fl_Counter.H>
#include "fl_gl_cyclic_color_wheel.h"

class gts_gui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *window_main_view;
private:
  inline void cb_window_main_view_i(Fl_Double_Window*, void*);
  static void cb_window_main_view(Fl_Double_Window*, void*);
  static Fl_Menu_Item menu_[];
  inline void cb_1_i(Fl_Menu_*, void*);
  static void cb_1(Fl_Menu_*, void*);
  inline void cb_11_i(Fl_Menu_*, void*);
  static void cb_11(Fl_Menu_*, void*);
  inline void cb__i(Fl_Menu_*, void*);
  static void cb_(Fl_Menu_*, void*);
  inline void cb_2_i(Fl_Menu_*, void*);
  static void cb_2(Fl_Menu_*, void*);
  inline void cb_3_i(Fl_Menu_*, void*);
  static void cb_3(Fl_Menu_*, void*);
  inline void cb_4_i(Fl_Menu_*, void*);
  static void cb_4(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_scan_crop;
private:
  inline void cb_menite_scan_crop_i(Fl_Menu_*, void*);
  static void cb_menite_scan_crop(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_preview_scan;
private:
  inline void cb_menite_preview_scan_i(Fl_Menu_*, void*);
  static void cb_menite_preview_scan(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_scan_save;
private:
  inline void cb_menite_scan_save_i(Fl_Menu_*, void*);
  static void cb_menite_scan_save(Fl_Menu_*, void*);
  inline void cb_Trace_i(Fl_Menu_*, void*);
  static void cb_Trace(Fl_Menu_*, void*);
  inline void cb_Rename_i(Fl_Menu_*, void*);
  static void cb_Rename(Fl_Menu_*, void*);
  inline void cb_Renumber_i(Fl_Menu_*, void*);
  static void cb_Renumber(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_area_and_rot90;
private:
  inline void cb_menite_area_and_rot90_i(Fl_Menu_*, void*);
  static void cb_menite_area_and_rot90(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_pixel_type_and_bright;
private:
  inline void cb_menite_pixel_type_and_bright_i(Fl_Menu_*, void*);
  static void cb_menite_pixel_type_and_bright(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_number;
private:
  inline void cb_menite_number_i(Fl_Menu_*, void*);
  static void cb_menite_number(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_scan_and_save;
private:
  inline void cb_menite_scan_and_save_i(Fl_Menu_*, void*);
  static void cb_menite_scan_and_save(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_trace_files;
private:
  inline void cb_menite_trace_files_i(Fl_Menu_*, void*);
  static void cb_menite_trace_files(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_trace_params;
private:
  inline void cb_menite_trace_params_i(Fl_Menu_*, void*);
  static void cb_menite_trace_params(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_trace_hsv_view;
private:
  inline void cb_menite_trace_hsv_view_i(Fl_Menu_*, void*);
  static void cb_menite_trace_hsv_view(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_trace_hue_minmax;
private:
  inline void cb_menite_trace_hue_minmax_i(Fl_Menu_*, void*);
  static void cb_menite_trace_hue_minmax(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_trace_batch;
private:
  inline void cb_menite_trace_batch_i(Fl_Menu_*, void*);
  static void cb_menite_trace_batch(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_sane_device;
private:
  inline void cb_5_i(Fl_Menu_*, void*);
  static void cb_5(Fl_Menu_*, void*);
  inline void cb_6_i(Fl_Menu_*, void*);
  static void cb_6(Fl_Menu_*, void*);
  inline void cb_7_i(Fl_Menu_*, void*);
  static void cb_7(Fl_Menu_*, void*);
  inline void cb_8_i(Fl_Menu_*, void*);
  static void cb_8(Fl_Menu_*, void*);
  inline void cb_9_i(Fl_Menu_*, void*);
  static void cb_9(Fl_Menu_*, void*);
  inline void cb_a_i(Fl_Menu_*, void*);
  static void cb_a(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_frame_cyclic;
private:
  inline void cb_b_i(Fl_Menu_*, void*);
  static void cb_b(Fl_Menu_*, void*);
  inline void cb_c_i(Fl_Menu_*, void*);
  static void cb_c(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_wview_main;
private:
  inline void cb_menite_wview_main_i(Fl_Menu_*, void*);
  static void cb_menite_wview_main(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_wview_sub;
private:
  inline void cb_menite_wview_sub_i(Fl_Menu_*, void*);
  static void cb_menite_wview_sub(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_wview_lr;
private:
  inline void cb_menite_wview_lr_i(Fl_Menu_*, void*);
  static void cb_menite_wview_lr(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_wview_ud;
private:
  inline void cb_menite_wview_ud_i(Fl_Menu_*, void*);
  static void cb_menite_wview_ud(Fl_Menu_*, void*);
  inline void cb_FullColor_i(Fl_Menu_*, void*);
  static void cb_FullColor(Fl_Menu_*, void*);
  inline void cb_Red_i(Fl_Menu_*, void*);
  static void cb_Red(Fl_Menu_*, void*);
  inline void cb_Green_i(Fl_Menu_*, void*);
  static void cb_Green(Fl_Menu_*, void*);
  inline void cb_Blue_i(Fl_Menu_*, void*);
  static void cb_Blue(Fl_Menu_*, void*);
  inline void cb_Red1_i(Fl_Menu_*, void*);
  static void cb_Red1(Fl_Menu_*, void*);
  inline void cb_Green1_i(Fl_Menu_*, void*);
  static void cb_Green1(Fl_Menu_*, void*);
  inline void cb_Blue1_i(Fl_Menu_*, void*);
  static void cb_Blue1(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_help_about;
private:
  inline void cb_menite_help_about_i(Fl_Menu_*, void*);
  static void cb_menite_help_about(Fl_Menu_*, void*);
public:
  fl_gl_image_view *image_view;
  Fl_Scrollbar *scrbar_view_x;
private:
  inline void cb_scrbar_view_x_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_view_x(Fl_Scrollbar*, void*);
public:
  Fl_Scrollbar *scrbar_view_y;
private:
  inline void cb_scrbar_view_y_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_view_y(Fl_Scrollbar*, void*);
public:
  Fl_Double_Window *window_next_scan;
  Fl_Button *button_rescan;
private:
  inline void cb_button_rescan_i(Fl_Button*, void*);
  static void cb_button_rescan(Fl_Button*, void*);
  inline void cb_Enter_i(Fl_Button*, void*);
  static void cb_Enter(Fl_Button*, void*);
  inline void cb_Esc_i(Fl_Button*, void*);
  static void cb_Esc(Fl_Button*, void*);
public:
  Fl_Output *norout_crnt_scan_level;
  Fl_Output *norout_crnt_scan_number;
  Fl_Output *norout_next_scan_number;
  Fl_Double_Window *window_next_scan_non_modal;
private:
  inline void cb_window_next_scan_non_modal_i(Fl_Double_Window*, void*);
  static void cb_window_next_scan_non_modal(Fl_Double_Window*, void*);
public:
  Fl_Output *norout_next_save_non_modal;
  Fl_Button *button_next_save_non_modal;
private:
  inline void cb_button_next_save_non_modal_i(Fl_Button*, void*);
  static void cb_button_next_save_non_modal(Fl_Button*, void*);
  inline void cb_Esc1_i(Fl_Button*, void*);
  static void cb_Esc1(Fl_Button*, void*);
public:
  Fl_Double_Window *window_area_and_rot90;
private:
  inline void cb_window_area_and_rot90_i(Fl_Double_Window*, void*);
  static void cb_window_area_and_rot90(Fl_Double_Window*, void*);
public:
  fltk_button_area_and_rot90 *button_area_and_rot90;
private:
  inline void cb_button_area_and_rot90_i(fltk_button_area_and_rot90*, void*);
  static void cb_button_area_and_rot90(fltk_button_area_and_rot90*, void*);
public:
  Fl_Value_Input *valinp_area_reso;
private:
  inline void cb_valinp_area_reso_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_reso(Fl_Value_Input*, void*);
public:
  Fl_Choice *choice_rot90;
private:
  inline void cb_choice_rot90_i(Fl_Choice*, void*);
  static void cb_choice_rot90(Fl_Choice*, void*);
  static Fl_Menu_Item menu_choice_rot90[];
public:
  Fl_Button *button_scan_crop;
private:
  inline void cb_button_scan_crop_i(Fl_Button*, void*);
  static void cb_button_scan_crop(Fl_Button*, void*);
public:
  Fl_Group *group_area_crop;
  Fl_Value_Input *valinp_area_offset_cm_x;
private:
  inline void cb_valinp_area_offset_cm_x_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_offset_cm_x(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_area_offset_cm_y;
private:
  inline void cb_valinp_area_offset_cm_y_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_offset_cm_y(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_area_size_cm_w;
private:
  inline void cb_valinp_area_size_cm_w_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_size_cm_w(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_area_size_cm_h;
private:
  inline void cb_valinp_area_size_cm_h_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_size_cm_h(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_area_size_pixel_w;
private:
  inline void cb_valinp_area_size_pixel_w_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_size_pixel_w(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_area_size_pixel_h;
private:
  inline void cb_valinp_area_size_pixel_h_i(Fl_Value_Input*, void*);
  static void cb_valinp_area_size_pixel_h(Fl_Value_Input*, void*);
public:
  Fl_Button *radbut_area_reso_fix_cm;
  Fl_Button *radbut_area_reso_fix_pixel;
private:
  inline void cb_Set_i(Fl_Button*, void*);
  static void cb_Set(Fl_Button*, void*);
  inline void cb_Set1_i(Fl_Button*, void*);
  static void cb_Set1(Fl_Button*, void*);
public:
  Fl_Output *txtout_scanner_type;
  Fl_Value_Output *valout_scanner_size_cm_w;
  Fl_Value_Output *valout_scanner_size_cm_h;
  Fl_Double_Window *window_pixel_type_and_bright;
private:
  inline void cb_window_pixel_type_and_bright_i(Fl_Double_Window*, void*);
  static void cb_window_pixel_type_and_bright(Fl_Double_Window*, void*);
public:
  fltk_button_pixel_type_and_bright *button_pixel_type_and_bright;
private:
  inline void cb_button_pixel_type_and_bright_i(fltk_button_pixel_type_and_bright*, void*);
  static void cb_button_pixel_type_and_bright(fltk_button_pixel_type_and_bright*, void*);
public:
  Fl_Choice *choice_pixel_type;
private:
  inline void cb_choice_pixel_type_i(Fl_Choice*, void*);
  static void cb_choice_pixel_type(Fl_Choice*, void*);
  static Fl_Menu_Item menu_choice_pixel_type[];
public:
  Fl_Group *group_bw;
  Fl_Value_Input *valinp_bw_threshold;
private:
  inline void cb_valinp_bw_threshold_i(Fl_Value_Input*, void*);
  static void cb_valinp_bw_threshold(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_bw_threshold;
private:
  inline void cb_scrbar_bw_threshold_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_bw_threshold(Fl_Scrollbar*, void*);
public:
  Fl_Group *group_grays;
  Fl_Value_Input *valinp_grayscale_brightness;
private:
  inline void cb_valinp_grayscale_brightness_i(Fl_Value_Input*, void*);
  static void cb_valinp_grayscale_brightness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_grayscale_brightness;
private:
  inline void cb_scrbar_grayscale_brightness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_grayscale_brightness(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_grayscale_contrast;
private:
  inline void cb_valinp_grayscale_contrast_i(Fl_Value_Input*, void*);
  static void cb_valinp_grayscale_contrast(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_grayscale_contrast;
private:
  inline void cb_scrbar_grayscale_contrast_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_grayscale_contrast(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_grayscale_gamma;
private:
  inline void cb_valinp_grayscale_gamma_i(Fl_Value_Input*, void*);
  static void cb_valinp_grayscale_gamma(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_grayscale_gamma;
private:
  inline void cb_scrbar_grayscale_gamma_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_grayscale_gamma(Fl_Scrollbar*, void*);
public:
  Fl_Group *group_rgb;
  Fl_Value_Input *valinp_rgb_brightness;
private:
  inline void cb_valinp_rgb_brightness_i(Fl_Value_Input*, void*);
  static void cb_valinp_rgb_brightness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_rgb_brightness;
private:
  inline void cb_scrbar_rgb_brightness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_rgb_brightness(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_rgb_contrast;
private:
  inline void cb_valinp_rgb_contrast_i(Fl_Value_Input*, void*);
  static void cb_valinp_rgb_contrast(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_rgb_contrast;
private:
  inline void cb_scrbar_rgb_contrast_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_rgb_contrast(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_rgb_gamma;
private:
  inline void cb_valinp_rgb_gamma_i(Fl_Value_Input*, void*);
  static void cb_valinp_rgb_gamma(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_rgb_gamma;
private:
  inline void cb_scrbar_rgb_gamma_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_rgb_gamma(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_preview_scan;
private:
  inline void cb_button_preview_scan_i(Fl_Button*, void*);
  static void cb_button_preview_scan(Fl_Button*, void*);
public:
  Fl_Double_Window *window_scan_and_save;
private:
  inline void cb_window_scan_and_save_i(Fl_Double_Window*, void*);
  static void cb_window_scan_and_save(Fl_Double_Window*, void*);
public:
  Fl_Check_Button *chkbtn_scan_filter_trace_sw;
private:
  inline void cb_chkbtn_scan_filter_trace_sw_i(Fl_Check_Button*, void*);
  static void cb_chkbtn_scan_filter_trace_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chkbtn_scan_filter_erase_dot_noise_sw;
private:
  inline void cb_chkbtn_scan_filter_erase_dot_noise_sw_i(Fl_Check_Button*, void*);
  static void cb_chkbtn_scan_filter_erase_dot_noise_sw(Fl_Check_Button*, void*);
public:
  Fl_File_Input *filinp_scan_save_dir_path;
private:
  inline void cb_filinp_scan_save_dir_path_i(Fl_File_Input*, void*);
  static void cb_filinp_scan_save_dir_path(Fl_File_Input*, void*);
  inline void cb_d_i(Fl_Button*, void*);
  static void cb_d(Fl_Button*, void*);
public:
  Fl_Input *strinp_scan_save_file_head;
private:
  inline void cb_strinp_scan_save_file_head_i(Fl_Input*, void*);
  static void cb_strinp_scan_save_file_head(Fl_Input*, void*);
public:
  Fl_Output *output_scan_save_number_format;
private:
  inline void cb_output_scan_save_number_format_i(Fl_Output*, void*);
  static void cb_output_scan_save_number_format(Fl_Output*, void*);
public:
  Fl_Choice *choice_scan_save_image_format;
private:
  inline void cb_choice_scan_save_image_format_i(Fl_Choice*, void*);
  static void cb_choice_scan_save_image_format(Fl_Choice*, void*);
public:
  Fl_Value_Input *valinp_scan_num_start;
  Fl_Choice *choice_scan_num_continue_type;
private:
  inline void cb_choice_scan_num_continue_type_i(Fl_Choice*, void*);
  static void cb_choice_scan_num_continue_type(Fl_Choice*, void*);
  static Fl_Menu_Item menu_choice_scan_num_continue_type[];
public:
  Fl_Choice *choice_scan_num_endless_direction;
  static Fl_Menu_Item menu_choice_scan_num_endless_direction[];
  Fl_Value_Input *valinp_scan_num_end;
private:
  inline void cb_e_i(Fl_Button*, void*);
  static void cb_e(Fl_Button*, void*);
public:
  Fl_Check_Button *chkbtn_scan_adjustable_per_frame_sw;
  Fl_Button *button_scan_save;
private:
  inline void cb_button_scan_save_i(Fl_Button*, void*);
  static void cb_button_scan_save(Fl_Button*, void*);
public:
  Fl_Double_Window *window_trace_files;
private:
  inline void cb_window_trace_files_i(Fl_Double_Window*, void*);
  static void cb_window_trace_files(Fl_Double_Window*, void*);
public:
  Fl_File_Input *filinp_trace_open_dir_path;
  Fl_Input *strinp_trace_open_file_head;
  Fl_Input *strinp_trace_open_number_format;
  Fl_Choice *choice_trace_open_image_format;
private:
  inline void cb_f_i(Fl_Button*, void*);
  static void cb_f(Fl_Button*, void*);
  inline void cb_Rename1_i(Fl_Button*, void*);
  static void cb_Rename1(Fl_Button*, void*);
  inline void cb_Renumber1_i(Fl_Button*, void*);
  static void cb_Renumber1(Fl_Button*, void*);
public:
  Fl_Check_Button *chkbtn_trace_filter_trace_sw;
private:
  inline void cb_chkbtn_trace_filter_trace_sw_i(Fl_Check_Button*, void*);
  static void cb_chkbtn_trace_filter_trace_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chkbtn_trace_filter_erase_dot_noise_sw;
private:
  inline void cb_chkbtn_trace_filter_erase_dot_noise_sw_i(Fl_Check_Button*, void*);
  static void cb_chkbtn_trace_filter_erase_dot_noise_sw(Fl_Check_Button*, void*);
public:
  Fl_File_Input *filinp_trace_save_dir_path;
private:
  inline void cb_filinp_trace_save_dir_path_i(Fl_File_Input*, void*);
  static void cb_filinp_trace_save_dir_path(Fl_File_Input*, void*);
  inline void cb_10_i(Fl_Button*, void*);
  static void cb_10(Fl_Button*, void*);
public:
  Fl_Input *strinp_trace_save_file_head;
private:
  inline void cb_strinp_trace_save_file_head_i(Fl_Input*, void*);
  static void cb_strinp_trace_save_file_head(Fl_Input*, void*);
public:
  Fl_Output *output_trace_save_number_format;
private:
  inline void cb_output_trace_save_number_format_i(Fl_Output*, void*);
  static void cb_output_trace_save_number_format(Fl_Output*, void*);
public:
  Fl_Choice *choice_trace_save_image_format;
private:
  inline void cb_choice_trace_save_image_format_i(Fl_Choice*, void*);
  static void cb_choice_trace_save_image_format(Fl_Choice*, void*);
public:
  Fl_Value_Output *valout_trace_num_start;
  Fl_Value_Output *valout_trace_num_end;
private:
  inline void cb_Set2_i(Fl_Button*, void*);
  static void cb_Set2(Fl_Button*, void*);
  inline void cb_Trace1_i(Fl_Button*, void*);
  static void cb_Trace1(Fl_Button*, void*);
public:
  Fl_Double_Window *window_number;
private:
  inline void cb_window_number_i(Fl_Double_Window*, void*);
  static void cb_window_number(Fl_Double_Window*, void*);
  static Fl_Menu_Item menu_1[];
  inline void cb_Select_i(Fl_Menu_*, void*);
  static void cb_Select(Fl_Menu_*, void*);
  inline void cb_Delete_i(Fl_Menu_*, void*);
  static void cb_Delete(Fl_Menu_*, void*);
public:
  Fl_Input *norinp_number_input;
private:
  inline void cb_norinp_number_input_i(Fl_Input*, void*);
  static void cb_norinp_number_input(Fl_Input*, void*);
public:
  Fl_Output *output_number_action_type;
  Fl_Output *output_number_file_head_name;
  Fl_Browser *selbro_number_list;
private:
  inline void cb_selbro_number_list_i(Fl_Browser*, void*);
  static void cb_selbro_number_list(Fl_Browser*, void*);
public:
  Fl_Double_Window *window_trace_batch;
private:
  inline void cb_window_trace_batch_i(Fl_Double_Window*, void*);
  static void cb_window_trace_batch(Fl_Double_Window*, void*);
  inline void cb_Add_i(Fl_Button*, void*);
  static void cb_Add(Fl_Button*, void*);
  inline void cb_Upper_i(Fl_Button*, void*);
  static void cb_Upper(Fl_Button*, void*);
  inline void cb_Lower_i(Fl_Button*, void*);
  static void cb_Lower(Fl_Button*, void*);
  inline void cb_Delete1_i(Fl_Button*, void*);
  static void cb_Delete1(Fl_Button*, void*);
  inline void cb_Run_i(Fl_Button*, void*);
  static void cb_Run(Fl_Button*, void*);
public:
  Fl_Browser *selbro_trace_batch_config_list;
  Fl_Double_Window *window_trace_params;
private:
  inline void cb_window_trace_params_i(Fl_Double_Window*, void*);
  static void cb_window_trace_params(Fl_Double_Window*, void*);
public:
  Fl_Group *group_trace_params;
  fltk_button_trace_params *button_trace_params;
private:
  inline void cb_button_trace_params_i(fltk_button_trace_params*, void*);
  static void cb_button_trace_params(fltk_button_trace_params*, void*);
  inline void cb_12_i(Fl_Button*, void*);
  static void cb_12(Fl_Button*, void*);
public:
  Fl_Button *togbut_trace_open_under_sw;
private:
  inline void cb_togbut_trace_open_under_sw_i(Fl_Button*, void*);
  static void cb_togbut_trace_open_under_sw(Fl_Button*, void*);
public:
  Fl_Button *togbut_trace_open_right_middle_sw;
private:
  inline void cb_togbut_trace_open_right_middle_sw_i(Fl_Button*, void*);
  static void cb_togbut_trace_open_right_middle_sw(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_display_target_sw;
private:
  inline void cb_chebut_trace_display_target_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_display_target_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_display_main_sw;
private:
  inline void cb_chebut_trace_display_main_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_display_main_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_0_enable_sw;
private:
  inline void cb_chebut_trace_0_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_0_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_0;
  Fl_Button *button_trace_0_target_rgb;
private:
  inline void cb_button_trace_0_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_0_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_0_thickness;
private:
  inline void cb_valinp_trace_0_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_0_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_0_thickness;
private:
  inline void cb_scrbar_trace_0_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_0_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_0_hue_min;
private:
  inline void cb_button_trace_0_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_0_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_0_hue_min;
private:
  inline void cb_valinp_trace_0_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_0_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_0_hue_max;
private:
  inline void cb_valinp_trace_0_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_0_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_0_hue_minmax;
private:
  inline void cb_button_trace_0_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_0_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_0_rotate360_sw;
private:
  inline void cb_chebut_trace_0_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_0_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_0_display_sw;
private:
  inline void cb_chebut_trace_0_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_0_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_0_slope_deg;
private:
  inline void cb_valinp_trace_0_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_0_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_0_intercept;
private:
  inline void cb_valinp_trace_0_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_0_intercept(Fl_Value_Input*, void*);
public:
  Fl_Check_Button *chebut_trace_1_enable_sw;
private:
  inline void cb_chebut_trace_1_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_1_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_1;
  Fl_Button *button_trace_1_target_rgb;
private:
  inline void cb_button_trace_1_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_1_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_1_thickness;
private:
  inline void cb_valinp_trace_1_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_1_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_1_thickness;
private:
  inline void cb_scrbar_trace_1_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_1_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_1_hue_min;
private:
  inline void cb_button_trace_1_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_1_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_1_hue_min;
private:
  inline void cb_valinp_trace_1_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_1_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_1_hue_max;
private:
  inline void cb_valinp_trace_1_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_1_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_1_hue_minmax;
private:
  inline void cb_button_trace_1_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_1_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_1_rotate360_sw;
private:
  inline void cb_chebut_trace_1_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_1_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_1_display_sw;
private:
  inline void cb_chebut_trace_1_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_1_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_1_slope_deg;
private:
  inline void cb_valinp_trace_1_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_1_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_1_intercept;
private:
  inline void cb_valinp_trace_1_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_1_intercept(Fl_Value_Input*, void*);
public:
  Fl_Check_Button *chebut_trace_2_enable_sw;
private:
  inline void cb_chebut_trace_2_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_2_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_2;
  Fl_Button *button_trace_2_target_rgb;
private:
  inline void cb_button_trace_2_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_2_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_2_thickness;
private:
  inline void cb_valinp_trace_2_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_2_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_2_thickness;
private:
  inline void cb_scrbar_trace_2_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_2_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_2_hue_min;
private:
  inline void cb_button_trace_2_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_2_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_2_hue_min;
private:
  inline void cb_valinp_trace_2_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_2_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_2_hue_max;
private:
  inline void cb_valinp_trace_2_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_2_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_2_hue_minmax;
private:
  inline void cb_button_trace_2_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_2_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_2_rotate360_sw;
private:
  inline void cb_chebut_trace_2_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_2_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_2_display_sw;
private:
  inline void cb_chebut_trace_2_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_2_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_2_slope_deg;
private:
  inline void cb_valinp_trace_2_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_2_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_2_intercept;
private:
  inline void cb_valinp_trace_2_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_2_intercept(Fl_Value_Input*, void*);
public:
  Fl_Check_Button *chebut_trace_3_enable_sw;
private:
  inline void cb_chebut_trace_3_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_3_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_3;
  Fl_Button *button_trace_3_target_rgb;
private:
  inline void cb_button_trace_3_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_3_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_3_thickness;
private:
  inline void cb_valinp_trace_3_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_3_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_3_thickness;
private:
  inline void cb_scrbar_trace_3_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_3_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_3_hue_min;
private:
  inline void cb_button_trace_3_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_3_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_3_hue_min;
private:
  inline void cb_valinp_trace_3_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_3_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_3_hue_max;
private:
  inline void cb_valinp_trace_3_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_3_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_3_hue_minmax;
private:
  inline void cb_button_trace_3_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_3_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_3_rotate360_sw;
private:
  inline void cb_chebut_trace_3_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_3_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_3_display_sw;
private:
  inline void cb_chebut_trace_3_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_3_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_3_slope_deg;
private:
  inline void cb_valinp_trace_3_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_3_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_3_intercept;
private:
  inline void cb_valinp_trace_3_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_3_intercept(Fl_Value_Input*, void*);
public:
  Fl_Check_Button *chebut_trace_4_enable_sw;
private:
  inline void cb_chebut_trace_4_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_4_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_4;
  Fl_Button *button_trace_4_target_rgb;
private:
  inline void cb_button_trace_4_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_4_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_4_thickness;
private:
  inline void cb_valinp_trace_4_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_4_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_4_thickness;
private:
  inline void cb_scrbar_trace_4_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_4_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_4_hue_min;
private:
  inline void cb_button_trace_4_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_4_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_4_hue_min;
private:
  inline void cb_valinp_trace_4_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_4_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_4_hue_max;
private:
  inline void cb_valinp_trace_4_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_4_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_4_hue_minmax;
private:
  inline void cb_button_trace_4_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_4_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_4_rotate360_sw;
private:
  inline void cb_chebut_trace_4_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_4_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_4_display_sw;
private:
  inline void cb_chebut_trace_4_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_4_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_4_slope_deg;
private:
  inline void cb_valinp_trace_4_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_4_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_4_intercept;
private:
  inline void cb_valinp_trace_4_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_4_intercept(Fl_Value_Input*, void*);
public:
  Fl_Check_Button *chebut_trace_5_enable_sw;
private:
  inline void cb_chebut_trace_5_enable_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_5_enable_sw(Fl_Check_Button*, void*);
public:
  Fl_Group *group_trace_5;
  Fl_Button *button_trace_5_target_rgb;
private:
  inline void cb_button_trace_5_target_rgb_i(Fl_Button*, void*);
  static void cb_button_trace_5_target_rgb(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_5_thickness;
private:
  inline void cb_valinp_trace_5_thickness_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_5_thickness(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_trace_5_thickness;
private:
  inline void cb_scrbar_trace_5_thickness_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_trace_5_thickness(Fl_Scrollbar*, void*);
public:
  Fl_Button *button_trace_5_hue_min;
private:
  inline void cb_button_trace_5_hue_min_i(Fl_Button*, void*);
  static void cb_button_trace_5_hue_min(Fl_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_5_hue_min;
private:
  inline void cb_valinp_trace_5_hue_min_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_5_hue_min(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_5_hue_max;
private:
  inline void cb_valinp_trace_5_hue_max_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_5_hue_max(Fl_Value_Input*, void*);
public:
  Fl_Button *button_trace_5_hue_minmax;
private:
  inline void cb_button_trace_5_hue_minmax_i(Fl_Button*, void*);
  static void cb_button_trace_5_hue_minmax(Fl_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_5_rotate360_sw;
private:
  inline void cb_chebut_trace_5_rotate360_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_5_rotate360_sw(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *chebut_trace_5_display_sw;
private:
  inline void cb_chebut_trace_5_display_sw_i(Fl_Check_Button*, void*);
  static void cb_chebut_trace_5_display_sw(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *valinp_trace_5_slope_deg;
private:
  inline void cb_valinp_trace_5_slope_deg_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_5_slope_deg(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *valinp_trace_5_intercept;
private:
  inline void cb_valinp_trace_5_intercept_i(Fl_Value_Input*, void*);
  static void cb_valinp_trace_5_intercept(Fl_Value_Input*, void*);
public:
  Fl_Button *button_change_0_1;
private:
  inline void cb_button_change_0_1_i(Fl_Button*, void*);
  static void cb_button_change_0_1(Fl_Button*, void*);
public:
  Fl_Button *button_change_1_2;
private:
  inline void cb_button_change_1_2_i(Fl_Button*, void*);
  static void cb_button_change_1_2(Fl_Button*, void*);
public:
  Fl_Button *button_change_2_3;
private:
  inline void cb_button_change_2_3_i(Fl_Button*, void*);
  static void cb_button_change_2_3(Fl_Button*, void*);
public:
  Fl_Button *button_change_3_4;
private:
  inline void cb_button_change_3_4_i(Fl_Button*, void*);
  static void cb_button_change_3_4(Fl_Button*, void*);
public:
  Fl_Button *button_change_4_5;
private:
  inline void cb_button_change_4_5_i(Fl_Button*, void*);
  static void cb_button_change_4_5(Fl_Button*, void*);
public:
  Fl_Double_Window *window_trace_hsv_view;
private:
  inline void cb_window_trace_hsv_view_i(Fl_Double_Window*, void*);
  static void cb_window_trace_hsv_view(Fl_Double_Window*, void*);
  static Fl_Menu_Item menu_2[];
public:
  static Fl_Menu_Item *menite_hsv_dot_normal;
private:
  inline void cb_menite_hsv_dot_normal_i(Fl_Menu_*, void*);
  static void cb_menite_hsv_dot_normal(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_hsv_dot_trace_area;
private:
  inline void cb_menite_hsv_dot_trace_area_i(Fl_Menu_*, void*);
  static void cb_menite_hsv_dot_trace_area(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_hsv_dot_white;
private:
  inline void cb_menite_hsv_dot_white_i(Fl_Menu_*, void*);
  static void cb_menite_hsv_dot_white(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_hsv_dot_black;
private:
  inline void cb_menite_hsv_dot_black_i(Fl_Menu_*, void*);
  static void cb_menite_hsv_dot_black(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menite_hsv_random_position;
private:
  inline void cb_menite_hsv_random_position_i(Fl_Menu_*, void*);
  static void cb_menite_hsv_random_position(Fl_Menu_*, void*);
public:
  fl_gl_hsv_view *hsv_view;
  Fl_Double_Window *window_set_number_format;
private:
  inline void cb_window_set_number_format_i(Fl_Double_Window*, void*);
  static void cb_window_set_number_format(Fl_Double_Window*, void*);
public:
  Fl_Choice *choice_input_num_form_separator;
private:
  inline void cb_choice_input_num_form_separator_i(Fl_Choice*, void*);
  static void cb_choice_input_num_form_separator(Fl_Choice*, void*);
public:
  Fl_Counter *counte_input_num_form_num_of_digits;
private:
  inline void cb_counte_input_num_form_num_of_digits_i(Fl_Counter*, void*);
  static void cb_counte_input_num_form_num_of_digits(Fl_Counter*, void*);
public:
  Fl_Output *output_input_num_form_sample;
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  Fl_Double_Window *window_set_aspect_ratio;
private:
  inline void cb_window_set_aspect_ratio_i(Fl_Double_Window*, void*);
  static void cb_window_set_aspect_ratio(Fl_Double_Window*, void*);
public:
  Fl_Button *radbut_area_aspect_ratio_w;
  Fl_Value_Input *valinp_area_aspect_ratio_w;
  Fl_Button *radbut_area_aspect_ratio_h;
  Fl_Value_Input *valinp_area_aspect_ratio_h;
private:
  inline void cb_OK1_i(Fl_Button*, void*);
  static void cb_OK1(Fl_Button*, void*);
  inline void cb_Cancel1_i(Fl_Button*, void*);
  static void cb_Cancel1(Fl_Button*, void*);
public:
  Fl_Double_Window *window_set_color;
private:
  inline void cb_window_set_color_i(Fl_Double_Window*, void*);
  static void cb_window_set_color(Fl_Double_Window*, void*);
public:
  Fl_Value_Input *valinp_set_color_hue;
private:
  inline void cb_valinp_set_color_hue_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_hue(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_hue;
private:
  inline void cb_scrbar_set_color_hue_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_hue(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_set_color_sat;
private:
  inline void cb_valinp_set_color_sat_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_sat(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_sat;
private:
  inline void cb_scrbar_set_color_sat_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_sat(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_set_color_val;
private:
  inline void cb_valinp_set_color_val_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_val(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_val;
private:
  inline void cb_scrbar_set_color_val_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_val(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_set_color_red;
private:
  inline void cb_valinp_set_color_red_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_red(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_red;
private:
  inline void cb_scrbar_set_color_red_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_red(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_set_color_gre;
private:
  inline void cb_valinp_set_color_gre_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_gre(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_gre;
private:
  inline void cb_scrbar_set_color_gre_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_gre(Fl_Scrollbar*, void*);
public:
  Fl_Value_Input *valinp_set_color_blu;
private:
  inline void cb_valinp_set_color_blu_i(Fl_Value_Input*, void*);
  static void cb_valinp_set_color_blu(Fl_Value_Input*, void*);
public:
  Fl_Scrollbar *scrbar_set_color_blu;
private:
  inline void cb_scrbar_set_color_blu_i(Fl_Scrollbar*, void*);
  static void cb_scrbar_set_color_blu(Fl_Scrollbar*, void*);
public:
  Fl_Box *box_set_color_ok;
  Fl_Box *box_set_color_cancel;
private:
  inline void cb_OK2_i(Fl_Button*, void*);
  static void cb_OK2(Fl_Button*, void*);
  inline void cb_Cancel2_i(Fl_Button*, void*);
  static void cb_Cancel2(Fl_Button*, void*);
public:
  Fl_Double_Window *window_trace_hue_minmax;
private:
  inline void cb_window_trace_hue_minmax_i(Fl_Double_Window*, void*);
  static void cb_window_trace_hue_minmax(Fl_Double_Window*, void*);
public:
  fl_gl_cyclic_color_wheel *cyclic_color_wheel;
  Fl_Button *radbut_hue_min_sw;
private:
  inline void cb_radbut_hue_min_sw_i(Fl_Button*, void*);
  static void cb_radbut_hue_min_sw(Fl_Button*, void*);
public:
  Fl_Button *radbut_hue_max_sw;
private:
  inline void cb_radbut_hue_max_sw_i(Fl_Button*, void*);
  static void cb_radbut_hue_max_sw(Fl_Button*, void*);
  inline void cb_Reset_i(Fl_Button*, void*);
  static void cb_Reset(Fl_Button*, void*);
};
extern gts_gui cl_gts_gui; 
#endif
