#ifndef __memory_config_trace_src_hls_h__
#define __memory_config_trace_src_hls_h__

#define STR_COLOR_TRACE_01_CHK		"color_trace_01_chk"
#define STR_COLOR_TRACE_01_HUE_MIN	"color_trace_01_hue_min"
#define STR_COLOR_TRACE_01_HUE_MAX	"color_trace_01_hue_max"
#define STR_COLOR_TRACE_01_LIG_MIN	"color_trace_01_lig_min"
#define STR_COLOR_TRACE_01_LIG_MAX	"color_trace_01_lig_max"
#define STR_COLOR_TRACE_01_SAT_MIN	"color_trace_01_sat_min"
#define STR_COLOR_TRACE_01_SAT_MAX	"color_trace_01_sat_max"
#define STR_COLOR_TRACE_01_TGT		"color_trace_01_tgt"
#define STR_COLOR_TRACE_02_CHK		"color_trace_02_chk"
#define STR_COLOR_TRACE_02_HUE_MIN	"color_trace_02_hue_min"
#define STR_COLOR_TRACE_02_HUE_MAX	"color_trace_02_hue_max"
#define STR_COLOR_TRACE_02_LIG_MIN	"color_trace_02_lig_min"
#define STR_COLOR_TRACE_02_LIG_MAX	"color_trace_02_lig_max"
#define STR_COLOR_TRACE_02_SAT_MIN	"color_trace_02_sat_min"
#define STR_COLOR_TRACE_02_SAT_MAX	"color_trace_02_sat_max"
#define STR_COLOR_TRACE_02_TGT		"color_trace_02_tgt"
#define STR_COLOR_TRACE_03_CHK		"color_trace_03_chk"
#define STR_COLOR_TRACE_03_HUE_MIN	"color_trace_03_hue_min"
#define STR_COLOR_TRACE_03_HUE_MAX	"color_trace_03_hue_max"
#define STR_COLOR_TRACE_03_LIG_MIN	"color_trace_03_lig_min"
#define STR_COLOR_TRACE_03_LIG_MAX	"color_trace_03_lig_max"
#define STR_COLOR_TRACE_03_SAT_MIN	"color_trace_03_sat_min"
#define STR_COLOR_TRACE_03_SAT_MAX	"color_trace_03_sat_max"
#define STR_COLOR_TRACE_03_TGT		"color_trace_03_tgt"
#define STR_COLOR_TRACE_04_CHK		"color_trace_04_chk"
#define STR_COLOR_TRACE_04_HUE_MIN	"color_trace_04_hue_min"
#define STR_COLOR_TRACE_04_HUE_MAX	"color_trace_04_hue_max"
#define STR_COLOR_TRACE_04_LIG_MIN	"color_trace_04_lig_min"
#define STR_COLOR_TRACE_04_LIG_MAX	"color_trace_04_lig_max"
#define STR_COLOR_TRACE_04_SAT_MIN	"color_trace_04_sat_min"
#define STR_COLOR_TRACE_04_SAT_MAX	"color_trace_04_sat_max"
#define STR_COLOR_TRACE_04_TGT		"color_trace_04_tgt"
#define STR_COLOR_TRACE_05_CHK		"color_trace_05_chk"
#define STR_COLOR_TRACE_05_HUE_MIN	"color_trace_05_hue_min"
#define STR_COLOR_TRACE_05_HUE_MAX	"color_trace_05_hue_max"
#define STR_COLOR_TRACE_05_LIG_MIN	"color_trace_05_lig_min"
#define STR_COLOR_TRACE_05_LIG_MAX	"color_trace_05_lig_max"
#define STR_COLOR_TRACE_05_SAT_MIN	"color_trace_05_sat_min"
#define STR_COLOR_TRACE_05_SAT_MAX	"color_trace_05_sat_max"
#define STR_COLOR_TRACE_05_TGT		"color_trace_05_tgt"
#define STR_COLOR_TRACE_06_CHK		"color_trace_06_chk"
#define STR_COLOR_TRACE_06_HUE_MIN	"color_trace_06_hue_min"
#define STR_COLOR_TRACE_06_HUE_MAX	"color_trace_06_hue_max"
#define STR_COLOR_TRACE_06_LIG_MIN	"color_trace_06_lig_min"
#define STR_COLOR_TRACE_06_LIG_MAX	"color_trace_06_lig_max"
#define STR_COLOR_TRACE_06_SAT_MIN	"color_trace_06_sat_min"
#define STR_COLOR_TRACE_06_SAT_MAX	"color_trace_06_sat_max"
#define STR_COLOR_TRACE_06_TGT		"color_trace_06_tgt"

#endif /* !__memory_config_trace_src_hls_h__ */
